name: Bump

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: 'bump'
  cancel-in-progress: true

jobs:
  check-version:
    uses: ./.github/workflows/check-version.yml

  bump:
    runs-on: ubuntu-latest
    needs: [check-version]
    if: needs.check-version.outputs.new-version == '1'
    defaults:
      run:
        working-directory: ./generator
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./generator/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run generator
        run: node out/generator/src/main

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          author: start-5 <start-5@users.noreply.github.com>
          committer: start-5 <start-5@users.noreply.github.com>
          branch: bump
          title: '[Automated] Bump'
          commit-message: '[Automated] Bump'
