name: Check game version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generator
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./generator/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check game version
        id: check-version
        run: node out/generator/src/version
        continue-on-error: true

      - name: Set output
        run: echo "new-version=${{ steps.check-version.outcome == 'success' && '1' || '0' }}" >> "$GITHUB_OUTPUT"
