name: Check game version

on:
  workflow_call:
    outputs:
      new-version:
        value: ${{ jobs.check-version.outputs.new-version }}
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.set-output.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./generator/package-lock.json

      - name: Install dependencies
        run: npm --prefix ./generator ci

      - name: Build
        run: npm --prefix ./generator run build

      - name: Check game version
        id: check-version
        run: node ./generator/out/generator/src/version
        continue-on-error: true

      - name: Set output
        id: set-output
        run: echo "new-version=${{ steps.check-version.outcome == 'success' && '1' || '0' }}" >> "$GITHUB_OUTPUT"
